
version: 2.1
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/orestes910/lambda_test
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go build -o weather
      - run: zip weather.zip weather
      - persist_to_workspace:
            paths:
                - weather.zip